### ISSUE TITLE
Layout Broken after Load

### ISSUE THREAD

**Issue by davidhellmann** [bigbitecreative/macy.js#19]
It's broken after load first time. My JS is in the Footer, maybe that's the problem. Whats a good Workaround to fix that? 

![image](https://cloud.githubusercontent.com/assets/764292/23759503/46cbbb0c-04ed-11e7-90d1-394db35f7972.png)

Link: https://davidhellmann.com/

**Comment by jrmd** [comment]
Hey @davidhellmann,

The issue is due to the images fading in the script can’t calculate the height, the easiest way to solve this is to run a Macy.recalculate() when they fade in.
 
Hope this helps.

Jerome

**Comment by P0WW0W** [comment]
Hello @jrmd,

I'm running into the same issue as @davidhellmann. Problem seems to be isolated to Safari, and not Chrome. My only fades are using CSS, and the fades are not targeting the images in "macy-container". 

![170312_screenshot](https://cloud.githubusercontent.com/assets/4086818/23830237/6ff24046-06dc-11e7-9ffe-70b90a1f4969.PNG)
See: http://reliablespice.com

Any chance you could be a little more descriptive with a fix?

Thanks,
Alexander

**Comment by jrmd** [comment]
Hi @P0WW0W I cant recreate this issue on latest safari are their any steps to reproduce?

**Comment by P0WW0W** [comment]
Hello @jrmd, Thanks for the quick reply.

To confirm, I'm also using Safari Version 10.0.3.

**Steps to recreate issue:**
1. Load [homepage](http://reliablespice.com)
2. Click any image link to the right hand side of the page
3. Use the home navigation button on the sub-page (upper left) to return back to the homepage.
4. Grid collapse upon load of homepage.

I'm guessing this has something to do with safari caching, because the problem is not expressed during development with live-reload on the same browser. Additionally, when the broken page is refreshed the grid loads normally again.

I appreciate the help,
Alexander

**Comment by jrmd** [comment]
Hey @P0WW0W ,

I cant recreate the issue still but as far as i can tell you just get macy to run after images have loaded so maybe the event is firing too quickly, as a fix you could try setting `waitForImages: true` in the init options

Thanks,
Jerome

**Comment by P0WW0W** [comment]
@jrmd thanks for taking a look. Interesting to hear the issue is not happening on your end. I have considered the 'waitForImages' option. Doesn't seem to resolve it. I'll continue to have a think on this one. The plugin works very well otherwise.

**Comment by Rubel-hossain** [comment]
adding the method in click method ,  macy.recalculate();
