### ISSUE TITLE
Multiple galleries in a page leads to second gallery breaking. 

### ISSUE THREAD

**Issue by thedonquixotic** [bigbitecreative/macy.js#34]
Hey, so I'm using Macy to build a custom wordpress gallery for myself. It's great!

I create a custom post type called Galleries, and then I use a wp program to insert the gallery into another post. So far, this all works fine. 

But when I insert two different galleries the second one doesn't run quite correctly. 

Here's how I init macy:

```
var macy_instance = Macy.init({
        container: '.gridGallery',
        trueOrder: false,
        waitForImages: true,
        debug: true,
        margin: 0,
        columns: 5,
        breakAt: {
            1200: 4,
            940: 3,
            520: 1
        }
    });
```

And I also call this later on in order to help with the lazy loader:

` macy_instance.runOnImageLoad(function () { macy_instance.recalculate(true); }, true);`

Issues with the second gallery:

1. Default columns are set to 5. Columns on second are 3 deep. 

2. Lazy loader works fine with gallery, but stuff isn't getting consistently repositioned in a masonry fashion. [image here](https://i.imgur.com/CcTIaSU.png)

If I delete the first gallery on the page, and then rerun the macy_instance code in the console, then the second gallery (now the only gallery) loads perfectly fine. If I run macy_instance init code in console without deleting the first gallery, the second gallery remains messed up. 

I think this has something to do with the container name, since both galleries are classed as .gridGallery. To confirm this I just ran the macy_instance with a different class name, which I assigned post loading the page to the second gallery and this time it worked. 

So I've got some ideas about how I could make this work in wordpress but was also hoping maybe there was a more lightweight way that was built into Macy, or some suggestions of the sort. Thanks!

Any pointers are appreciated thank you!

**Comment by thedonquixotic** [comment]
I got a WP centric fix working, by passing the gallery post title to the .gridGallery target as an additional class name, and then running the script within each individual gallery post. But this might not be the most efficient way to do things, and probably wouldn't help anyone else who wants to do multiple macy galleries on a single page, so would love to know more about how to do this in a more vanilla fashion if possible, just because I'm new to coding and trying to learn as much as possible.

**Comment by jrmd** [comment]
Hi @thedonquixotic

Sorry for the late response, I must've missed this notification.

The issue you are mentioning seems to be caused by you only initialising Macy once, whereas you need to be creating a Macy instance per 'gallery'.

To resolve this issue you could run a for loop and give each gallery an ID an then create a Macy instance for each gallery.

```
var galleries = document.querySelectorAll('.gridGallery');
var macyInstances = [];
var macyOptions = {
  trueOrder: false,
  waitForImages: true,
  debug: true,
  margin: 0,
  columns: 5,
  breakAt: {
    1200: 4,
    940: 3,
    520: 1
  }
};

for (var i = 0; i < galleries.length; i++) {
  var newId = 'galleryinstance-' + i;
  galleries[i].id = newId;
  macyOptions.container = '#' + newId;
  macyInstances.push(Macy(macyOptions));
}

```

Unfortunately, Macy doesn't support passing elements directly, but this is something I'll look to fix in the future. 

Secondly, I noticed you initialized Macy using `Macy.init` whereas this is now deprecated and will be removed in later versions. I would recommend initialising Macy by either doing `Macy({ opts })` or doing `new Macy({ opts });`

In the latest version, that is almost ready for publishing I have updated the image loading code which works using promises; this, unfortunately, requires using a polyfill to support IE11. Using promises is a much more reliable way to do this.

In addition to the previous, I also added a way to use a different image loading script if you want.

Thanks,
Jerome

**Comment by thedonquixotic** [comment]
Thanks! That's super helpful!
